version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: graylog-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: graylog-opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  graylog:
    image: graylog/graylog:6.0
    container_name: graylog
    depends_on:
      - mongodb
      - opensearch
    restart: unless-stopped
    environment:
      # segredo usado para criptografar tokens e senhas internas
      - GRAYLOG_PASSWORD_SECRET=some-long-password-secret-change-me
      # senha do usu√°rio admin: "admin"
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.0.2:9000/
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
    ports:
      - "192.168.0.2:9000:9000"          # Web UI
      - "192.168.0.2:12201:12201/udp"    # GELF UDP
      - "192.168.0.2:12201:12201/tcp"    # GELF TCP

volumes:
  mongo_data:
  opensearch_data:
